from urllib.parse import urljoin
import requests
import time 
from argparse import Namespace
# from web_search.bing_search import bing_web_search
# from web_search.bing_search import extract_relevant_info

import asyncio
from openai import OpenAI
# from deep_search_dgt import deep_search_dgt
from transformers import AutoTokenizer
# class Searcher:
#     def __init__(self, api_url, max_retries=3, retry_delay=1):
#         self.api_url = api_url.rstrip("/")
#         self.max_retries = max_retries
#         self.retry_delay = retry_delay

#     def search(self, query, num=10):
#         endpoint = urljoin(self.api_url, "/search")
#         for attempt in range(self.max_retries):
#             try:
#                 response = requests.post(endpoint, json={"query": query, "num": num}, timeout=10)
#                 response.raise_for_status()  # Raise an error for bad responses
#                 result = response.json()
#                 return result["results"]
#             except requests.Timeout as e:
#                 print(f"Search timeout error: {str(e)}")
#                 if attempt == self.max_retries - 1:
#                     return []
#                 time.sleep(self.retry_delay)
#             except requests.RequestException as e:
#                 print(f"Search client error: {str(e)}")
#                 if attempt == self.max_retries - 1:
#                     return []
#                 time.sleep(self.retry_delay)
#             except Exception as e:
#                 print(f"Search error: {str(e)}")
#                 if attempt == self.max_retries - 1:
#                     print(f"Search failed after {self.max_retries} attempts: {str(e)}")
#                     raise
#                 time.sleep(self.retry_delay)
#         return []





def debug_code_function(code, error):

    API_BASE_URL = "your api url"
    # API_BASE_URL = "http://192.168.1.1:4396/v1"
    MODEL_NAME = "Qwen2.5-7B-Instruct"
    client = OpenAI(
        api_key="empty",
        base_url=API_BASE_URL,
    )

    prompt = f"""You are a code expert. I need you to debug the following code. Below are the code originally generated by the model and the error information that occurred during code execution. Please output ONLY the corrected Python code, without any explanation or markdown formatting:

    **Inputs:**

    **Original Code:**
    {code}

    **Execution Error:**
    {error}

    Output the corrected Python code only, without any explanation or markdown formatting:
    """

    chat_response = client.chat.completions.create(
        model=MODEL_NAME,
        messages=[
            {
                "role": "user",
                "content": prompt,
            }
        ],
    )
    
    response_text = chat_response.choices[0].message.content
    
    # 提取Python代码
    if "```python" in response_text and "```" in response_text:
        # 如果代码被markdown格式包围，提取其中的代码
        code_start = response_text.find("```python") + 9
        code_end = response_text.find("```", code_start)
        extracted_code = response_text[code_start:code_end].strip()
    else:
        # 如果没有markdown格式，直接使用返回的内容
        extracted_code = response_text.strip()
    # import pdb
    # pdb.set_trace()
    print("提取的代码:", extracted_code)
    return extracted_code






if __name__ == "__main__":

    # 测试用例：一个有语法错误的代码
    code = """
# 创建符号变量
x, y = symbols('x y')

# 定义方程
eq1 = x**2 + y**2 = 25  # 错误的等号使用
eq2 = 2*x + y = 10

# 求解方程组
solution = solve((eq1, eq2), (x, y))
print(f"Solution: {solution}")
    """
    
    error = "SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '=' ?"
    
    # 调用debug函数
    debug_code_function(code, error)
    # extracted_info = ''
    
    
    # question = "三角形的勾股定理是什么"


    # #调用纯bing
    # extracted_info = deep_search_dgt(
    #     search_query=question,
    #     use_jina=False,
    #     jina_api_key="empty",
    #     bing_subscription_key="d73c4b858f3f457a845598c4859e178b",
    #     bing_endpoint="https://api.bing.microsoft.com/v7.0/search"
    #     )
    # print('-------------------------------------')
    # print(extracted_info)
    # print('-------------------------------------')


    # #调用纯bing + summarizer
    # summarize_result = deep_search_dgt_with_summarize(
    #     search_query=question,
    #     use_jina=False,
    #     jina_api_key="empty",
    #     bing_subscription_key="d73c4b858f3f457a845598c4859e178b",
    #     bing_endpoint="https://api.bing.microsoft.com/v7.0/search"
    #     )
    # print('-------------------------------------')
    # print(summarize_result)
    # print('-------------------------------------')

# # Run the async function
# asyncio.run(main())
    
    
    
    
    
    
    
    
#     print("--------------------------------调用bing search url--------------------------------")
#     search_api = "http://183.174.229.164:1241"
#     # search_result = deep_search_dgt(search_api, search_content, top_k=5)

#     # # searcher = Searcher(search_api)


#     # # search_results = searcher.search(search_content, num=5)
#     search_results=asyncio.run(searcher.search(search_content, num=5))

#     result = ''
#     for info in search_results:
#         # info['snippet'] = formatted_documents
#         result+=info['snippet']

#     extracted_info = result

#     print("--------------------------------离开bing search url--------------------------------")


#                         # extracted_info = response
#     search_result = extracted_info
#     print(search_result)